spring.application.name=eliberari-api
app.ocr.input-folder=D:/DEV/IN/
app.ocr.output-folder=D:/DEV/OUT/
app.ocr.lot-folder=D:/DEV/LOT/
app.ocr.foxit-path=C:/Program Files (x86)/Foxit Software/Foxit PDF Reader/FoxitPDFReader.exe

# Configurare pentru upload fișiere mari
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB