spring.application.name=eliberari-api
app.ocr.input-folder=D:/DEV/IN/
app.ocr.output-folder=D:/DEV/OUT/
app.ocr.username=zoltan.verdes
app.ocr.password=xxxx
app.ocr.auth-server-url=https://sso.onrc.sii
app.ocr.realm=internal-onrc
app.ocr.client-id=rc-app